# CMake generated Testfile for 
# Source directory: /home/nonroot/shared/oops_updated/oops/coupled/test
# Build directory: /home/nonroot/shared/oops_updated/oops/build/coupled/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_coupled_geometry_qg_l95]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_geometry_qg_l95" "testinput/coupledgeometry.yaml")
set_tests_properties([=[test_coupled_geometry_qg_l95]=] PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;50;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_geometry_qg_l95_parallel]=] "/opt/views/view/bin/mpiexec" "-n" "2" "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_geometry_qg_l95_parallel" "testinput/coupledgeometryparallel.yaml")
set_tests_properties([=[test_coupled_geometry_qg_l95_parallel]=] PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable;mpi" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;446;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;56;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_modelauxcontrol_qg_l95]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_modelauxcontrol_qg_l95" "testinput/coupledmodelauxcontrol.yaml")
set_tests_properties([=[test_coupled_modelauxcontrol_qg_l95]=] PROPERTIES  ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;63;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_state_qg_l95]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_state_qg_l95" "testinput/coupledstate.yaml")
set_tests_properties([=[test_coupled_state_qg_l95]=] PROPERTIES  DEPENDS "test_qg_truth;test_l95_3dvar" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;69;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_state_qg_l95_parallel]=] "/opt/views/view/bin/mpiexec" "-n" "2" "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_state_qg_l95_parallel" "testinput/coupledstateparallel.yaml")
set_tests_properties([=[test_coupled_state_qg_l95_parallel]=] PROPERTIES  DEPENDS "test_qg_truth;test_l95_3dvar" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable;mpi" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;446;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;76;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_increment_qg_l95]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_increment_qg_l95" "testinput/coupledincrement.yaml")
set_tests_properties([=[test_coupled_increment_qg_l95]=] PROPERTIES  DEPENDS "test_qg_truth;test_l95_3dvar" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;84;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_convertstate_qg_l95]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_convertstate_qg_l95" "testinput/coupledconvertstate.yaml")
set_tests_properties([=[test_coupled_convertstate_qg_l95]=] PROPERTIES  DEPENDS "test_qg_truth;test_l95_3dvar" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;91;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_model_qg_l95]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_model_qg_l95" "testinput/coupledmodel.yaml")
set_tests_properties([=[test_coupled_model_qg_l95]=] PROPERTIES  DEPENDS "test_qg_truth;test_l95_3dvar" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;98;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_model_qg_l95_parallel]=] "/opt/views/view/bin/mpiexec" "-n" "2" "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_model_qg_l95_parallel" "testinput/coupledmodelparallel.yaml")
set_tests_properties([=[test_coupled_model_qg_l95_parallel]=] PROPERTIES  DEPENDS "test_qg_truth;test_l95_3dvar" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable;mpi" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;446;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;105;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_forecast_qg_l95]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_forecast_qg_l95" "testinput/forecast_qg_l95.yaml")
set_tests_properties([=[test_coupled_forecast_qg_l95]=] PROPERTIES  DEPENDS "test_qg_truth;test_l95_3dvar" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;113;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
add_test([=[test_coupled_hofx3d_qg_qg]=] "/home/nonroot/shared/oops_updated/oops/build/coupled/test/test_coupled_hofx3d_qg_qg" "testinput/hofx3d_qg_qg.yaml")
set_tests_properties([=[test_coupled_hofx3d_qg_qg]=] PROPERTIES  DEPENDS "test_qg_truth;test_qg_make_obs_4d_12h" ENVIRONMENT "OMP_NUM_THREADS=1" LABELS "oops;executable" _BACKTRACE_TRIPLES "/opt/views/._view/cimg64v3ckgivk7zqxf3vyx3wfc3nvek/share/ecbuild/cmake/ecbuild_add_test.cmake;448;add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;120;ecbuild_add_test;/home/nonroot/shared/oops_updated/oops/coupled/test/CMakeLists.txt;0;")
set_directory_properties(PROPERTIES LABELS "oops")
